@extends('layouts')

@section('title', '')

@section('metadata')
    <link rel="canonical" href="{{ route('privacy') }}">

    <meta content="" name="description">
    <meta content="" name="keywords">

    <meta property="og:type" content="">
    <meta property="og:url" content="{{ route('privacy') }}">
    <meta property="og:title" content="">
    <meta property="og:description" content="">
    <meta property="og:site_name" content="">
@endsection

@section('content')
    <section class="section-bg">
        <div class="container">
            <h2 class="mt-5">Privacy Policy</h2>
            <p class="fw-bold small">Last updated on September 1, 2023</p>

            <h5>1. Data Controller</h5>
            <p>Following the consultation of the website
                <a href="https://www.garofaloandpartners.it/">https://www.garofaloandpartners.it/</a>,
                by virtue of sending an email through the "Contact" section or to an email address indicated
                on the Website, personal data concerning identified or identifiable individuals ("Processing")
                may be processed.</p>
            <p>This document describes to users the methods of managing the Processing
                and also constitutes information provided in accordance with Article 13
                of Legislative Decree no. 196/2003, the Personal Data Protection Code ("Code"),
                and Article 13 of EU Regulation no. 2016/679 ("GDPR").</p>
            <p>The Data Controller is Garofalo & Partners Srls.</p>
            <br>
            <h5>2. Processed Data</h5>
            <p class="fw-bold">2.1 Navigation Data</p>
            <p>The computer systems and software procedures used for the operation of the Website acquire,
                during their normal operation, certain personal data whose transmission is implicit
                in the use of internet communication protocols.</p>
            <p>These are pieces of information not collected to be associated with identified individuals
                but which, by their nature, could allow the identification of users.</p>
            <p>This category of data includes IP addresses or domain names of the computers used
                by users connecting to the Website, the URI (Uniform Resource Identifier) addresses
                of the requested resources, the time of the request, the method used to submit the request
                to the server, the size of the file obtained in response, the numerical code indicating
                the status of the response given by the server (successful, error), and other parameters
                relating to the user's operating system and computing environment.</p>
            <p>These data are used solely for the purpose of obtaining anonymous statistical
                information about the use of the Website and to ensure its proper functioning.
                They are immediately deleted after processing.</p>
            <p>The Website does not use cookies for the transmission of personal information,
                nor are persistent cookies used, which are systems for tracking users.</p>
            <p>The use of session cookies (which are not stored persistently on the user's computer
                and disappear when the browser is closed) is strictly limited to the transmission of session
                identifiers (consisting of random numbers generated by the server) necessary to allow secure
                and efficient browsing of the Website.</p>
            <p>The session cookies used on this site avoid the use of other potentially detrimental computer
                techniques for the confidentiality of users' browsing and do not allow the acquisition
                of the user's identifiable personal data.</p>
            <p class="fw-bold">2.2 Voluntarily Provided Data</p>
            <p>The optional, explicit, and voluntary sending of emails to the addresses indicated on the Website
                or communications sent through the "Contact" section involves the subsequent acquisition
                of the sender's address, necessary to respond to requests, as well as any other personal data
                entered in such communications.</p>
            <br>
            <h5>3. Nature of Data and Consequences of Refusal to Respond</h5>
            <p>Apart from what is specified with reference to navigation data, which is necessary in order
                to allow users to use the Website correctly, data subjects are free to provide their personal data
                to request a response from Garofalo & Partners Srls. Failure to provide data may make it impossible
                to obtain the requested information.</p>
            <br>
            <h5>4. Processing Methods</h5>
            <p>Personal data is processed using manual, computerized, and automated systems
                for the time necessary to achieve the purposes for which it is collected.</p>
            <p>The Data Controller has implemented specific security measures to ensure that the Processing
                is carried out in compliance with the Code, with particular regard to preventing the loss
                of such data, unlawful or incorrect use, or unauthorized access to the databases.</p>
            <br>
            <h5>5. Data Subject's Rights</h5>
            <p>Users have the right at any time to obtain confirmation of the existence or
                not of personal data concerning them and their communication in intelligible form.</p>
            <p>Data subjects have the right to obtain information about:</p>
            <p class="fw-bold">the content and origin of personal data;</p>
            <p class="fw-bold">the purposes and methods of Processing;</p>
            <p class="fw-bold">the logic applied to the Processing carried out with the help
                of electronic instruments;</p>
            <p class="fw-bold">the identity of the Data Controller and Data Processors;</p>
            <p>the subjects or categories of subjects to whom the personal data may be communicated
                or who may become aware of it as Data Processors or Persons in Charge.</p>
            <p>Data subjects also have the right to obtain:</p>
            <p class="fw-bold">the updating, rectification, or, where interested, integration of data;</p>
            <p class="fw-bold">the deletion, anonymization, or blocking of data processed unlawfully,
                including data that do not need to be stored in relation to the purposes for which
                it was collected or subsequently processed;</p>
            <p>certification that the operations referred to above have been made known,
                also as regards their content, to those to whom the data has been communicated or disseminated,
                except where this proves impossible or involves a use of means disproportionate
                to the protected right.</p>
            <p>Data subjects have the right to object, in whole or in part, for legitimate reasons,
                to the Processing of personal data concerning them, even if it is relevant to the purpose
                of collection.</p>
            <p>To exercise the aforementioned rights, users can write to the data protection
                officer responsible for responding to the rights of users, Ing. Biagio Garofalo,
                by sending a communication to the following email address: emailaddress, indicating
                "Privacy - exercise of rights pursuant to Article 7 of Legislative Decree 196/2003"
                in the subject line.</p>
            <p>Data may also be processed by other Data Processors. The complete list of Data Processors
                is available at the registered office of the company Gecal.</p>
            <br>
            <h5>6. Communication and Disclosure of Data</h5>
            <p>The personal data collected on the Website is not subject to disclosure
                or communication and will not be sold or transferred to third parties.</p>
            <p>The communication or disclosure of data requested, in any case, is subject to compliance
                with the law by police forces, the judicial authority, information and security agencies,
                or other public subjects for the purposes of defense or State security, or for the prevention,
                investigation, or suppression of crimes.</p>
        </div>
    </section>
@endsection
